
let m_cloud_permission =  {
    AdminUser : {
        Dashboard:'O', Dashboard__Payment:'O',
        Payment:'O',
        Station:'O', Station__Add_Station:'O',
        StationDetail:'O', StationDetail__Reset:'O', StationDetail__Update:'O',
        StationEdit:'O', StationEdit__Edit:'O',
        EVSE:'O', EVSE__Add_EVSE:'O', EVSE__Reset:'O', EVSE__Update:'O',
        EVSEDetail:'O', EVSEDetail__Delete:'O', EVSEDetail__Edit:'O',
        EVSEEdit:'O',
        RatePlan:'O', RatePlan__Add_Rate_Plan:'O', RatePlan__Delete:'O', RatePlan__Copy:'O',RatePlan__Edit:'O',
        RatePlanDetail:'O', RatePlanDetail__Add_Rate_Plan:'O',
        User:'O', User__Add_User:'O', User__User_Detail:'O',
        UserDetail:'O', UserDetail__Clear:'O', UserDetail__User_Edit:'O', UserDetail__Card_Details:'O', UserDetail__Device_Detail:'O', UserDetail__Add_RFID:'O',
        RfidUser:'O', RfidUser__Add_User:'O', RfidUser__User_Detail:'O',
        RfidUserDetail:'O', RfidUserDetail__User_Edit:'O', RfidUserDetail__Add_RFID:'O',
        Company:'O', Company__Add_Company:'O', Company__Detail:'O',
        Administrator:'O',
        EVSELog:'O',
        ErrorLog:'O',
        SoftwareInfo:'O', SoftwareInfo__Add_SW_Release:'O', SoftwareInfo__Add_FW_Release:'O', SoftwareInfo__Release:'O', SoftwareInfo__Detail:'O',
        Parking:'O',
        AdminInfo:'O',
        Program:'O', Program__Add_Program:'O', Program__Detail:'O',
        ChargingProfile:'O', ChargingProfile__Add_Profile:'O', ChargingProfile__Detail:'O',
    },
    DeveloperUser : {
        Dashboard:'O',
        Payment:'O',
        Station:'O', Station__Add_Station:'O',
        StationDetail:'O', StationDetail__Reset:'O', StationDetail__Update:'O',
        StationEdit:'O', StationEdit__Edit:'O',
        EVSE:'O', EVSE__Add_EVSE:'O', EVSE__Reset:'O', EVSE__Update:'O',
        EVSEDetail:'O', EVSEDetail__Delete:'O', EVSEDetail__Edit:'O',
        EVSEEdit:'O',
        RatePlan:'O', RatePlan__Add_Rate_Plan:'O', RatePlan__Delete:'O', RatePlan__Copy:'O',RatePlan__Edit:'O',
        RatePlanDetail:'O', RatePlanDetail__Add_Rate_Plan:'O',
        User:'O', User__Add_User:'O', User__User_Detail:'O',
        UserDetail:'O', UserDetail__Clear:'O', UserDetail__User_Edit:'O', UserDetail__Card_Details:'O', UserDetail__Device_Detail:'O', UserDetail__Add_RFID:'O',
        Company:'O', Company__Add_Company:'O', Company__Detail:'O',
        Administrator:'O',
        EVSELog:'O',
        ErrorLog:'O',
        SoftwareInfo:'O', SoftwareInfo__Add_SW_Release:'O', SoftwareInfo__Add_FW_Release:'O', SoftwareInfo__Release:'O', SoftwareInfo__Detail:'O',
        Parking:'O',
        AdminInfo:'O',
        Program:'O', Program__Add_Program:'O', Program__Detail:'O',
        ChargingProfile:'O', ChargingProfile__Add_Profile:'O', ChargingProfile__Detail:'O',
    },
    FAEUser : {
        Dashboard:'X',
        Payment:'X',
        Station:'O', Station__Add_Station:'O',
        StationDetail:'O', StationDetail__Reset:'O', StationDetail__Update:'O',
        StationEdit:'O', StationEdit__Edit:'O',
        EVSE:'O', EVSE__Add_EVSE:'O', EVSE__Reset:'O', EVSE__Update:'O',
        EVSEDetail:'O', EVSEDetail__Delete:'X', EVSEDetail__Edit:'O',
        EVSEEdit:'O',
        RatePlan:'O', RatePlan__Add_Rate_Plan:'O', RatePlan__Delete:'O', RatePlan__Copy:'O',RatePlan__Edit:'O',
        RatePlanDetail:'O', RatePlanDetail__Add_Rate_Plan:'O',
        User:'O', User__Add_User:'X', User__User_Detail:'O',
        UserDetail:'O', UserDetail__Clear:'X', UserDetail__User_Edit:'X', UserDetail__Card_Details:'X', UserDetail__Device_Detail:'X', UserDetail__Add_RFID:'O',
        Company:'O', Company__Add_Company:'X', Company__Detail:'X',
        Administrator:'O',
        EVSELog:'O',
        ErrorLog:'O',
        SoftwareInfo:'O', SoftwareInfo__Add_SW_Release:'X', SoftwareInfo__Add_FW_Release:'X', SoftwareInfo__Release:'X', SoftwareInfo__Detail:'X',
        Parking:'O',
        AdminInfo:'X',
        Program:'X', Program__Add_Program:'X', Program__Detail:'X',
        ChargingProfile:'O', ChargingProfile__Add_Profile:'O', ChargingProfile__Detail:'O',
    },
    ViewerUser : {
        Dashboard:'O',
        Payment:'O',
        Station:'O', Station__Add_Station:'X',
        StationDetail:'O', StationDetail__Reset:'X', StationDetail__Update:'X',
        StationEdit:'O', StationEdit__Edit:'O',
        EVSE:'O', EVSE__Add_EVSE:'O', EVSE__Reset:'O', EVSE__Update:'O',
        EVSEDetail:'O', EVSEDetail__Delete:'X', EVSEDetail__Edit:'X',
        EVSEEdit:'R',
        RatePlan:'O', RatePlan__Add_Rate_Plan:'X', RatePlan__Delete:'X', RatePlan__Copy:'X',RatePlan__Edit:'O',
        RatePlanDetail:'O', RatePlanDetail__Add_Rate_Plan:'X',
        User:'O', User__Add_User:'X', User__User_Detail:'O',
        UserDetail:'O', UserDetail__Clear:'X', UserDetail__User_Edit:'X', UserDetail__Card_Details:'X', UserDetail__Device_Detail:'X', UserDetail__Add_RFID:'X',
        Company:'O', Company__Add_Company:'X', Company__Detail:'X',
        Administrator:'O',
        EVSELog:'O',
        ErrorLog:'O',
        SoftwareInfo:'O', SoftwareInfo__Add_SW_Release:'X', SoftwareInfo__Add_FW_Release:'X', SoftwareInfo__Release:'X', SoftwareInfo__Detail:'X',
        Parking:'O',
        AdminInfo:'X',
        Program:'O', Program__Add_Program:'X', Program__Detail:'X',
        ChargingProfile:'O', ChargingProfile__Add_Profile:'X', ChargingProfile__Detail:'X',
    },
    CustomerServiceUser : {
        Dashboard:'X',
        Payment:'O',
        Station:'O', Station__Add_Station:'X',
        StationDetail:'O', StationDetail__Reset:'O', StationDetail__Update:'X',
        StationEdit:'R', StationEdit__Edit:'X',
        EVSE:'O', EVSE__Add_EVSE:'X', EVSE__Reset:'O', EVSE__Update:'X',
        EVSEDetail:'O', EVSEDetail__Delete:'X', EVSEDetail__Edit:'X',
        EVSEEdit:'R',
        RatePlan:'O', RatePlan__Add_Rate_Plan:'X', RatePlan__Delete:'X', RatePlan__Copy:'X',RatePlan__Edit:'O',
        RatePlanDetail:'R', RatePlanDetail__Add_Rate_Plan:'X',
        User:'O', User__Add_User:'X', User__User_Detail:'O',
        UserDetail:'O', UserDetail__Clear:'X', UserDetail__User_Edit:'X', UserDetail__Card_Details:'X', UserDetail__Device_Detail:'X', UserDetail__Add_RFID:'X',
        Company:'O', Company__Add_Company:'X', Company__Detail:'X',
        Administrator:'O',
        EVSELog:'O',
        ErrorLog:'O',
        SoftwareInfo:'O', SoftwareInfo__Add_SW_Release:'X', SoftwareInfo__Add_FW_Release:'X', SoftwareInfo__Release:'X', SoftwareInfo__Detail:'X',
        Parking:'O',
        AdminInfo:'X',
        Program:'O', Program__Add_Program:'X', Program__Detail:'X',
        ChargingProfile:'X', ChargingProfile__Add_Profile:'X', ChargingProfile__Detail:'X',
    },
    EngineerUser : {
        Dashboard:'X',
        Payment:'X',
        Station:'X', Station__Add_Station:'X',
        StationDetail:'X', StationDetail__Reset:'X', StationDetail__Update:'X',
        StationEdit:'X', StationEdit__Edit:'X',
        EVSE:'X', EVSE__Add_EVSE:'X', EVSE__Reset:'X', EVSE__Update:'X',
        EVSEDetail:'X', EVSEDetail__Delete:'X', EVSEDetail__Edit:'X',
        EVSEEdit:'X',
        RatePlan:'X', RatePlan__Add_Rate_Plan:'X', RatePlan__Delete:'X', RatePlan__Copy:'X',RatePlan__Edit:'X',
        RatePlanDetail:'X', RatePlanDetail__Add_Rate_Plan:'X',
        User:'X', User__Add_User:'X', User__User_Detail:'X',
        UserDetail:'X', UserDetail__Clear:'X', UserDetail__User_Edit:'X', UserDetail__Card_Details:'X', UserDetail__Device_Detail:'X', UserDetail__Add_RFID:'X',
        Company:'X', Company__Add_Company:'X', Company__Detail:'X',
        Administrator:'X',
        EVSELog:'X',
        ErrorLog:'X',
        SoftwareInfo:'X', SoftwareInfo__Add_SW_Release:'X', SoftwareInfo__Add_FW_Release:'X', SoftwareInfo__Release:'X', SoftwareInfo__Detail:'X',
        Parking:'X',
        AdminInfo:'X',
        Program:'X', Program__Add_Program:'X', Program__Detail:'X',
        ChargingProfile:'X', ChargingProfile__Add_Profile:'X', ChargingProfile__Detail:'X',
    },
}

export { m_cloud_permission }